# Generated by Django 6.1.1 on 2026-09-11 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test1_yunet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='weekly_day',
            field=models.IntegerField(blank=True, choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], help_text='Day of week for recurring session (0=Monday, 6=Sunday)', null=True),
        ),
        migrations.AddField(
            model_name='session',
            name='weekly_end_time',
            field=models.TimeField(blank=True, help_text='End time for weekly session (e.g. 10:00)', null=True),
        ),
        migrations.AddField(
            model_name='session',
            name='weekly_start_time',
            field=models.TimeField(blank=True, help_text='Start time for weekly session (e.g. 09:00)', null=True),
        ),
    ]
